'use client';
import {useState,useEffect,useMemo,useCallback} from 'react';
import dynamic from 'next/dynamic';
import {useForm} from 'react-hook-form';
import {z} from 'zod';
import {zodResolver} from '@hookform/resolvers/zod';
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';
import {Compass,Search,Building2,Layers,CheckCheck,ArrowUpRight,Download,SlidersHorizontal,X,Settings2,ChevronLeft,ChevronRight,Table2,Map as MapIcon,ExternalLink,Loader2} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {callApi,initialBase,validBase,type Entity,type Geo} from '@/lib/client';
import demo from '@/lib/demo.json';
const MapView=dynamic(()=>import('./map'),{ssr:false,loading:()=> <div className="empty">Loading map…</div>});
const schema=z.object({terms:z.array(z.string().trim().min(1).max(100)).min(1,'Add a search term.').max(15),location:z.any().refine(v=>v?.provider_id,'Select a location.'),scope:z.enum(['city','radius']),radius:z.coerce.number().positive().max(100)});
type Form=z.infer<typeof schema>;
type Filters=Record<string,string>;
const emptyFilters:Filters={search:'',entity_type:'',category:'',specialty:'',min_rating:'',min_reviews:'',has_website:'',has_email:'',has_whatsapp:'',max_distance:''};
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string}){return <Select value={value} onValueChange={v=>onChange(v??'')}><SelectTrigger aria-label={label} className="w-full h-[42px] bg-white"><SelectValue>{options.find(x=>x[0]===value)?.[1]||label}</SelectValue></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Workspace(){
 const [base,setBase]=useState(initialBase),[apiKey,setApiKey]=useState(''),[connect,setConnect]=useState(false),[draftBase,setDraftBase]=useState(initialBase),[draftKey,setDraftKey]=useState('');
 const [mode,setMode]=useState('demo'),[term,setTerm]=useState(''),[geoInput,setGeoInput]=useState('kad'),[geoQuery,setGeoQuery]=useState('kad');
 const [jobId,setJobId]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [filters,setFilters]=useState<Filters>(emptyFilters),[showFilters,setShowFilters]=useState(false),[sort,setSort]=useState('name'),[page,setPage]=useState(1),[view,setView]=useState('table'),[bbox,setBbox]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[profile,setProfile]=useState<Entity|null>(null),[exportOpen,setExportOpen]=useState(false),[format,setFormat]=useState('xlsx'),[exportScope,setExportScope]=useState('filtered'),[exportBusy,setExportBusy]=useState(false);
 const [center,setCenter]=useState<Geo>(demo.location),[resultRadius,setResultRadius]=useState<number|null>(25);
 const form=useForm<Form>({resolver:zodResolver(schema),defaultValues:{terms:demo.terms,location:demo.location,scope:'radius',radius:25}});
 const terms=form.watch('terms'),location=form.watch('location'),scope=form.watch('scope');
 useEffect(()=>{const timer=setTimeout(()=>setGeoQuery(geoInput.length>=2?geoInput:'kad'),300);return()=>clearTimeout(timer)},[geoInput]);
 const api=(path:string,init?:RequestInit)=>callApi(base,apiKey,path,init);
 const locations=useQuery({queryKey:['locations',base,mode,geoQuery,apiKey],queryFn:()=>api('/api/locations/autocomplete?q='+encodeURIComponent(geoQuery)+'&mode='+mode),enabled:!!base,staleTime:60000,retry:1});
 const suggestions:Geo[]=base?(locations.data||[]):demo.locations.filter(x=>x.display_name.toLowerCase().includes(geoQuery.toLowerCase()));
 const meta=useQuery({queryKey:['meta',base,apiKey],queryFn:()=>api('/api/meta'),enabled:!!base,retry:false});
 const history=useQuery({queryKey:['history',base,apiKey,jobId],queryFn:()=>api('/api/search-jobs'),enabled:!!base,retry:false});
 const jobQuery=useQuery({queryKey:['job',jobId,base,apiKey],queryFn:()=>api('/api/search-jobs/'+jobId),enabled:!!jobId,refetchInterval:q=>q.state.data&&['completed','partially_completed','failed','cancelled'].includes(q.state.data.stage)?false:1000});
 const job=jobQuery.data,active=job&&!['completed','partially_completed','failed','cancelled'].includes(job.stage);
 const queryFilters={...filters,...(view==='map'&&bbox?{bbox}:{})};
 const params=new URLSearchParams({job_id:jobId||'',page:String(page),page_size:view==='map'?'100':'10',sort,...Object.fromEntries(Object.entries(queryFilters).filter(([,v])=>v!==''))});
 const results=useQuery({queryKey:['entities',jobId,base,apiKey,params.toString(),job?.stage],queryFn:()=>api('/api/entities?'+params),enabled:!!jobId&&!!job&&['completed','partially_completed'].includes(job.stage),retry:false});
 const detail=useQuery({queryKey:['profile',profile?.id,jobId,base,apiKey],queryFn:()=>api('/api/entities/'+profile?.id),enabled:!!jobId&&!!profile,retry:false});
 const demoRows=useMemo(()=>{const rows=(demo.entities as unknown as Entity[]).filter(e=>(!filters.search||(e.name+' '+e.address).toLowerCase().includes(filters.search.toLowerCase()))&&(!filters.entity_type||e.entity_type===filters.entity_type)&&(!filters.category||e.category===filters.category)&&(!filters.specialty||e.specialties.includes(filters.specialty))&&(!filters.min_rating||e.rating!==null&&e.rating>=+filters.min_rating)&&(!filters.min_reviews||e.review_count!==null&&e.review_count>=+filters.min_reviews)&&(!filters.max_distance||e.distance_km!==null&&e.distance_km<=+filters.max_distance)&&['website','email','whatsapp'].every(k=>!filters['has_'+k]||(filters['has_'+k]==='true')===!!(e as any)[k]));const k=sort.replace('-','');rows.sort((a:any,b:any)=>{if(a[k]==null)return 1;if(b[k]==null)return -1;return(typeof a[k]==='number'?a[k]-b[k]:String(a[k]).localeCompare(String(b[k])))*(sort.startsWith('-')?-1:1)});return rows},[filters,sort]);
 const total=jobId?(results.data?.total||0):demoRows.length,rows:Entity[]=jobId?(results.data?.items||[]):view==='map'?demoRows:demoRows.slice((page-1)*10,page*10),shown=detail.data||profile;
 useEffect(()=>{setPage(1);setSelected([])},[filters,jobId]);
 const filter=(key:string,value:string)=>setFilters(f=>({...f,[key]:value}));
 function addTerm(){const v=term.trim();if(v&&terms.length<15&&!terms.includes(v)){form.setValue('terms',[...terms,v],{shouldValidate:true});setTerm('')}}
 async function start(data:Form){setError('');setNotice('');setBusy(true);try{if(data.scope==='city'&&!data.location.bounding_box)throw Error('City bounds unavailable. Choose radius scope.');const j=await api('/api/search-jobs',{method:'POST',body:JSON.stringify({terms:data.terms,location:data.location,scope:data.scope,radius_km:data.scope==='radius'?Number(data.radius):null,mode})});setJobId(j.id);setCenter(data.location);setResultRadius(data.scope==='radius'?Number(data.radius):null);setFilters(emptyFilters)}catch(e){setError((e as Error).message);if(!base)setConnect(true)}finally{setBusy(false)}}
 async function cancel(){try{await api('/api/search-jobs/'+jobId+'/cancel',{method:'POST'});await jobQuery.refetch()}catch(e){setError((e as Error).message)}}
 function openJob(j:any){setJobId(j.id);setCenter(j.request.location);setResultRadius(j.request.scope==='radius'?j.request.radius_km:null);form.reset({terms:j.request.terms,location:j.request.location,scope:j.request.scope,radius:j.request.radius_km||25});setMode(j.request.mode);setFilters(emptyFilters)}
 async function download(){setExportBusy(true);setError('');try{if(!jobId)throw Error('Run a discovery job on the connected API before exporting. This initial table is a read-only fixture preview.');let ex=await api('/api/exports',{method:'POST',body:JSON.stringify({job_id:jobId,format,scope:exportScope,entity_ids:selected,filters:exportScope==='filtered'?queryFilters:{}})});for(let i=0;i<120&&ex.status==='queued';i++){await new Promise(r=>setTimeout(r,500));ex=await api('/api/exports/'+ex.id)}if(ex.status!=='completed')throw Error(ex.error||'Export is still processing. Retry shortly.');const r=await fetch(validBase(base)+'/api/exports/'+ex.id+'/download',{headers:apiKey?{'X-API-Key':apiKey}:{}});if(!r.ok)throw Error('Download failed');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='fieldatlas-'+ex.id+'.'+format;a.click();URL.revokeObjectURL(url);setExportOpen(false);setNotice('Export downloaded.')}catch(e){setError((e as Error).message)}finally{setExportBusy(false)}}
 const onSelect=useCallback((e:Entity)=>setProfile(e),[]);
 const currentError=error||results.error?.message||jobQuery.error?.message;
 return <div><header className="topbar"><a className="brand" href="/"><Compass size={27}/>FieldAtlas<span>WORKSPACE</span></a><div className="toolbar-right"><span className="demo-label">{jobId?(job?.request?.mode==='live'?'Live source data':'Fictional development data'):'Fictional preview'}</span><button className="secondary" onClick={()=>setConnect(true)} aria-label="API connection settings"><Settings2 size={17}/><span className="desktop-label">{meta.data?'API connected':'Connect API'}</span></button></div></header><main>
 <div className="eyebrow">BUSINESS DISCOVERY / {center.city?.toUpperCase()||'EXPLORER'}</div><div className="heading-row"><div><h1>Explore your local landscape.</h1><p>Discover businesses. Understand the details. Take the next step.</p></div><span className="pill"><span className="dot"/>{jobId?'Search workspace':'Sample workspace'}</span></div>
 <form className="search-panel" onSubmit={form.handleSubmit(start)}><div><label htmlFor="search-terms">What are you looking for?</label><div className="chips">{terms.map(t=><span key={t}>{t}<button type="button" aria-label={'Remove '+t} onClick={()=>form.setValue('terms',terms.filter(v=>v!==t),{shouldValidate:true})}><X size={13}/></button></span>)}<input id="search-terms" value={term} onChange={e=>setTerm(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addTerm()}}} placeholder="Add term +"/><button type="button" onClick={addTerm} aria-label="Add search term">+</button></div>{form.formState.errors.terms&&<small className="field-error">{form.formState.errors.terms.message}</small>}</div>
 <div><label>Where?</label><Combobox items={suggestions.map(x=>x.display_name)} value={location?.display_name||null} onValueChange={v=>{const g=suggestions.find(x=>x.display_name===v);if(g)form.setValue('location',g)}} onInputValueChange={(v,details)=>{setGeoInput(v);if(details.reason==='input-change'&&v!==location?.display_name)form.setValue('location',null)}}><ComboboxInput aria-label="Search location" placeholder="Type a city…" className="h-[46px] w-full"/><ComboboxContent><ComboboxEmpty>{locations.isFetching?'Looking up places…':'No matching locations'}</ComboboxEmpty><ComboboxList>{(v:string)=><ComboboxItem key={v} value={v}>{v}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox>{form.formState.errors.location&&<small className="field-error">Select a canonical location.</small>}</div>
 <div><label>Search area</label><Choice label="Search scope" value={scope} onChange={v=>form.setValue('scope',v as 'city'|'radius')} options={[['radius','Radius'],['city','City bounds']]}/>{scope==='radius'&&<div className="radius-control"><input aria-label="Radius in kilometers" type="number" min="1" max="100" {...form.register('radius')}/><span>km</span>{[5,10,25,50].map(r=><button type="button" key={r} onClick={()=>form.setValue('radius',r)}>{r}</button>)}</div>}</div><button className="primary" disabled={busy||active}>{busy?<Loader2 size={17} className="animate-spin"/>:<Search size={17}/>}Start discovery</button>
 <div className="search-options"><Choice label="Source mode" value={mode} onChange={v=>{setMode(v);form.setValue('location',null)}} options={[['demo','Fictional demo'],['live','Live · OpenStreetMap']]}/><span>Enter to add a term · up to 15 terms{locations.error?' · Location service unavailable':''}</span></div></form>
 {currentError&&<div role="alert" className="error">{currentError}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
 {job&&<div className="job-progress"><div className="heading-row"><div><strong>{job.stage.replaceAll('_',' ')}</strong><p>{job.raw_observations} observations · {job.unique_entities} businesses · {job.entities_enriched} enriched</p></div>{active&&<button className="secondary" onClick={cancel}>Cancel job</button>}<span>{job.progress_percent}%</span></div><Progress value={job.progress_percent}/>{job.errors?.length>0&&<details><summary>{job.errors.length} processing issue(s)</summary>{job.errors.map((e:any,i:number)=><p key={i}>{e.source||e.stage}: {e.error}</p>)}</details>}{job.query_variants?.length>0&&<details><summary>View {job.query_variants.length} deterministic query variants</summary><p>{job.query_variants.join(' · ')}</p></details>}</div>}
 <div className="section-title"><div><h2>{center.city||'Regional'} business landscape</h2><p>{resultRadius?resultRadius+' km radius':'City bounds'} · {jobId?'Search results':'Fictional development preview'}</p></div><button className="secondary" onClick={()=>setExportOpen(true)} disabled={active||!total}><Download size={16}/>Export results</button></div>
 <section className="metrics">{[[Building2,String(jobId?job?.unique_entities||0:12),'Unique businesses','Canonical entities'],[Layers,String(jobId?job?.raw_observations||0:13),'Source observations',jobId?(job?.duplicate_merges||0)+' duplicate merges':'Preserved with provenance'],[CheckCheck,String(total),'Matching businesses','Current filters applied'],[ArrowUpRight,String(selected.length),'Selected businesses','Ready for a focused export']].map(([Icon,n,l,s]:any)=><div className="metric" key={l}><span>{l}<Icon size={19}/></span><strong>{n}</strong><small>{s}</small></div>)}</section>
 <section className="results"><div className="results-toolbar"><Tabs value={view} onValueChange={v=>{setView(String(v));setPage(1);setBbox('')}}><TabsList><TabsTrigger value="table"><Table2 size={15}/>Table</TabsTrigger><TabsTrigger value="map"><MapIcon size={15}/>Map</TabsTrigger></TabsList></Tabs><div className="toolbar-right"><label className="search-small"><Search size={16}/><input aria-label="Search businesses" placeholder="Search businesses…" value={filters.search} onChange={e=>filter('search',e.target.value)}/></label><button className="secondary" onClick={()=>setShowFilters(!showFilters)} aria-expanded={showFilters}><SlidersHorizontal size={16}/>Filters<span className="count">{Object.values(filters).filter(Boolean).length}</span></button></div></div>
 {showFilters&&<div className="filter-grid"><label>Entity type<Choice label="Entity type filter" value={filters.entity_type} onChange={v=>filter('entity_type',v)} options={[['','All types'],...['hospital','clinic','doctor','school','restaurant','hotel','retail','gym'].map(x=>[x,x] as [string,string])]}/></label>{[['category','Category','Healthcare'],['specialty','Specialty','Orthopedics']].map(([k,l,p])=><label key={k}>{l}<input value={filters[k]} placeholder={p} onChange={e=>filter(k,e.target.value)}/></label>)}{[['min_rating','Minimum rating','5'],['min_reviews','Minimum reviews','10000000'],['max_distance','Maximum distance (km)','100']].map(([k,l,max])=><label key={k}>{l}<input type="number" min="0" max={max} step={k==='min_rating'?'0.1':'1'} value={filters[k]} onChange={e=>filter(k,e.target.value)}/></label>)}{[['has_website','Website'],['has_email','Email'],['has_whatsapp','WhatsApp']].map(([k,l])=><label key={k}>{l}<Choice label={l+' filter'} value={filters[k]} onChange={v=>filter(k,v)} options={[['','Any'],['true','Available'],['false','Unknown / unavailable']]}/></label>)}<button className="secondary" onClick={()=>setFilters(emptyFilters)}>Clear filters</button></div>}
 <div className="sortbar"><span>{selected.length?selected.length+' selected':total+' businesses'}{selected.length>0&&<button className="link" onClick={()=>setSelected([])}>Clear selection</button>}</span><Choice label="Sort results" value={sort} onChange={v=>{setSort(v);setPage(1)}} options={[['name','Name A–Z'],['-name','Name Z–A'],['distance_km','Nearest first'],['-rating','Highest rating'],['-review_count','Most reviews'],['-completeness_score','Most complete'],['-source_count','Most sources']]}/></div>
 {view==='map'?<><MapView rows={rows} center={center} radius={resultRadius} onSelect={onSelect} onBounds={setBbox}/><p className="map-note">{total>100?'Showing up to 100 markers. Zoom in for a smaller area.':'Map and table use the same filters. Pan or zoom to query the visible area.'}</p></>:<Table><TableHeader><TableRow><TableHead><Checkbox aria-label="Select current page" checked={!!rows.length&&rows.every(e=>selected.includes(e.id))} onCheckedChange={v=>setSelected(v?Array.from(new Set([...selected,...rows.map(e=>e.id)])):selected.filter(id=>!rows.some(e=>e.id===id)))}/></TableHead>{['Business / Provider','Category / Specialties','City','Distance','Rating / Reviews','Phone','Website','Email','WhatsApp','Sources','Completeness','Confidence'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((e,i)=><TableRow key={e.id}><TableCell><Checkbox aria-label={'Select '+e.name} checked={selected.includes(e.id)} onCheckedChange={v=>setSelected(v?[...selected,e.id]:selected.filter(id=>id!==e.id))}/></TableCell><TableCell><button className="business-cell text-left" onClick={()=>setProfile(e)}><span className={'avatar tone-'+i%3}><Building2 size={18}/></span><span><strong>{e.name}</strong><small>{e.entity_type||'Type unknown'}{e.possible_duplicate?' · Possible duplicate':''}</small></span></button></TableCell><TableCell><span className="tag">{e.category||'Uncategorized'}</span><small className="block mt-2">{e.specialties.join(', ')||'—'}</small></TableCell><TableCell>{e.city||'—'}</TableCell><TableCell>{e.distance_km!==null?e.distance_km+' km':'—'}</TableCell><TableCell>{e.rating??'—'} / {e.review_count??'—'}</TableCell><TableCell>{e.phone||'—'}</TableCell><TableCell>{e.website?<a href={e.website} target="_blank" rel="noopener noreferrer" className="link">Visit <ExternalLink size={12} className="inline"/></a>:'—'}</TableCell><TableCell>{e.email||'—'}</TableCell><TableCell>{e.whatsapp?'Available':'—'}</TableCell><TableCell>{e.source_count}</TableCell><TableCell><div className="score"><i style={{width:e.completeness_score+'%'}}/></div>{e.completeness_score}%</TableCell><TableCell><span className="confidence">{e.confidence}</span></TableCell></TableRow>)}</TableBody></Table>}
 {view==='table'&&!rows.length&&<div className="empty">{results.isFetching?'Loading results…':active?'Discovery is running. Results will appear here.':'No businesses match these filters.'}</div>}
 {view==='table'&&<div className="pagination"><span>Showing {total?((page-1)*10+1):0}–{Math.min(page*10,total)} of {total}</span><div className="toolbar-right"><button className="secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)} aria-label="Previous page"><ChevronLeft size={15}/></button><span>Page {page} of {Math.max(1,Math.ceil(total/10))}</span><button className="secondary" disabled={page*10>=total} onClick={()=>setPage(p=>p+1)} aria-label="Next page"><ChevronRight size={15}/></button></div></div>}</section>
 {history.data?.length>0&&<details className="recent-jobs"><summary>Recent searches</summary>{history.data.map((j:any)=><button key={j.id} className="history-row" onClick={()=>openJob(j)}><span>{j.request.location.display_name} · {j.request.terms.join(', ')}</span><small>{j.stage.replaceAll('_',' ')}</small></button>)}</details>}
 <footer>{jobId&&job?.request?.mode==='live'?'Source coverage varies. Unknown values remain empty; ratings are shown only when supplied by a source.':'Fictional development fixtures. These are not real discovered businesses. Unknown contact and rating fields remain empty.'}</footer></main>
 <Sheet open={!!profile} onOpenChange={o=>{if(!o)setProfile(null)}}><SheetContent className="sm:max-w-[560px] w-full"><div className="profile"><SheetTitle>{shown?.name||'Business profile'}</SheetTitle><SheetDescription>{shown?.is_demo?'Fictional development record':'Public business information and provenance'}</SheetDescription>{detail.isFetching&&<p>Loading evidence…</p>}{detail.error&&<p className="error">{detail.error.message}</p>}{shown&&<><h3>Overview</h3><dl>{[['Entity type',shown.entity_type],['Facility type',shown.facility_type],['Category',shown.category],['Address',shown.address],['City',shown.city],['Phone',shown.phone],['Email',shown.email],['WhatsApp',shown.whatsapp],['Website',shown.website],['Rating / reviews',(shown.rating??'—')+' / '+(shown.review_count??'—')],['Completeness',shown.completeness_score+'%'],['Confidence',shown.confidence],['Sources',shown.source_count],['Last verified',shown.last_verified_at]].map(([k,v])=><div key={String(k)} className="contents"><dt>{k}</dt><dd className="break-words">{v||'Unknown'}</dd></div>)}</dl><h3>Categories and services</h3>{['specialties','subspecialties','services'].map(k=><p key={k}><strong className="capitalize">{k}: </strong>{(shown as any)[k]?.join(', ')||'Unknown'}</p>)}<h3>Evidence</h3>{shown.evidence?.map((e:any,i:number)=><div className="evidence-card" key={i}><strong>{e.attribute_name}: {e.value_text}</strong><p>{e.extraction_method} · {e.confidence>=.85?'High':e.confidence>=.6?'Medium':'Low'} confidence</p><p>{e.evidence_text}</p>{e.source_url&&<a className="link" href={e.source_url} target="_blank" rel="noopener noreferrer">{e.source_name||'Source'}</a>}</div>)}<h3>Source observations</h3>{shown.sources?.map((s:any,i:number)=><div className="evidence-card" key={i}><strong>{s.source}</strong><p>{s.name} · {s.source_record_id}</p><p>Query: {s.query_used}</p><p>Retrieved: {s.retrieved_at}</p>{s.source_url&&<a href={s.source_url} target="_blank" rel="noopener noreferrer" className="link">Open source</a>}</div>)}</>}</div></SheetContent></Sheet>
 <Dialog open={connect} onOpenChange={setConnect}><DialogContent><DialogTitle>Connect your API</DialogTitle><DialogDescription>Use a local API or managed HTTPS backend. The API key stays in memory for this session.</DialogDescription><div className="api-panel"><label>API base URL<input value={draftBase} onChange={e=>setDraftBase(e.target.value)} placeholder="https://your-api.onrender.com"/></label><label>Workspace API key<input type="password" value={draftKey} onChange={e=>setDraftKey(e.target.value)} autoComplete="off" placeholder="Optional for local demo"/></label><button className="primary" onClick={async()=>{try{const url=validBase(draftBase);await callApi(url,draftKey,'/api/meta');setBase(url);setApiKey(draftKey);setJobId(null);setConnect(false);setError('');setNotice('API connected. Start a discovery job to explore and export results.')}catch(e){setError((e as Error).message)}}}>Connect API</button>{error&&<p className="field-error">{error}</p>}</div></DialogContent></Dialog>
 <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent><DialogTitle>Export business data</DialogTitle><DialogDescription>Excel includes Businesses, Categories, Sources, and Search Metadata.</DialogDescription><div className="api-panel"><Choice label="Export format" value={format} onChange={setFormat} options={[['xlsx','Excel workbook (.xlsx)'],['csv','CSV (.csv)'],['json','JSON (.json)']]}/><Choice label="Export scope" value={exportScope} onChange={setExportScope} options={[['filtered','Filtered results'],['all','All job results'],['selected','Selected businesses ('+selected.length+')']]}/><button className="primary" disabled={exportBusy||(exportScope==='selected'&&!selected.length)} onClick={download}>{exportBusy?<Loader2 size={17} className="animate-spin"/>:<Download size={17}/>}Download export</button>{error&&<p className="field-error">{error}</p>}</div></DialogContent></Dialog>
 </div>
}
export default function Page(){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{refetchOnWindowFocus:false}}}));return <QueryClientProvider client={client}><Workspace/></QueryClientProvider>}

